# Generated by Django 4.1.7 on 2023-03-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_roles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='Rol',
        ),
    ]
