# Generated by Django 4.1.7 on 2023-03-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='passport',
            field=models.IntegerField(unique=True),
        ),
    ]
